In [2]:
import pandas as pd
pd.set_option('display.max_columns',None)
#pd.set_option('display.max_rows',None)

In [3]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import scipy

import sklearn
from sklearn.preprocessing import StandardScaler

In [12]:
hcc_data = pd.read_csv(r"C:\Users\catar\OneDrive\Ambiente de Trabalho\1 ano\s2\eiacd\projeto2_cd\hcc_dataset.csv")
hcc_data

,Gender,Symptoms,Alcohol,HBsAg,HBeAg,HBcAb,HCVAb,Cirrhosis,Endemic,Smoking,Diabetes,Obesity,Hemochro,AHT,CRI,HIV,NASH,Varices,Spleno,PHT,PVT,Metastasis,Hallmark,Age,Grams_day,Packs_year,PS,Encephalopathy,Ascites,INR,AFP,Hemoglobin,MCV,Leucocytes,Platelets,Albumin,Total_Bil,ALT,AST,GGT,ALP,TP,Creatinine,Nodules,Major_Dim,Dir_Bil,Iron,Sat,Ferritin,Class
0,Male,No,Yes,No,No,No,No,Yes,No,Yes,Yes,?,Yes,No,No,No,No,Yes,No,No,No,No,Yes,67,137,15,Active,NaN,NaN,1.53,95,13.7,106.6,4.9,99,3.4,2.1,34,41,183,150,7.1,0.7,1,3.5,0.5,?,?,?,Lives
1,Female,?,No,No,No,No,Yes,Yes,?,?,Yes,No,No,Yes,No,No,No,Yes,No,No,No,No,Yes,62,0,?,Active,NaN,NaN,?,?,?,?,?,?,?,?,?,?,?,?,?,?,1,1.8,?,?,?,?,Lives
2,Male,No,Yes,Yes,No,Yes,No,Yes,No,Yes,No,No,No,Yes,Yes,No,No,No,No,Yes,No,Yes,Yes,78,50,50,Ambulatory,NaN,Mild,0.96,5.8,8.9,79.8,8.4,472,3.3,0.4,58,68,202,109,7,2.1,5,13,0.1,28,6,16,Lives
3,Male,Yes,Yes,No,No,No,No,Yes,No,Yes,Yes,No,No,Yes,No,No,No,No,No,No,No,Yes,Yes,77,40,30,Active,NaN,NaN,0.95,2440,13.4,97.1,9,279,3.7,0.4,16,64,94,174,8.1,1.11,2,15.7,0.2,?,?,?,Dies
4,Male,Yes,Yes,Yes,No,Yes,No,Yes,No,Yes,No,No,No,Yes,Yes,No,No,No,No,No,No,No,Yes,76,100,30,Active,NaN,NaN,0.94,49,14.3,95.1,6.4,199,4.1,0.7,147,306,173,109,6.9,1.8,1,9,?,59,15,22,Lives
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,Female,No,Yes,?,?,?,Yes,Yes,No,Yes,No,No,No,No,No,Yes,No,No,No,No,No,No,No,40,?,?,Active,NaN,NaN,0.84,?,15.4,109.2,9.3,184000,4.6,0.5,35,40,449,109,7.6,0.7,5,3,?,?,?,?,Lives
161,Female,Yes,No,?,?,?,?,Yes,No,No,No,No,No,Yes,No,?,No,Yes,Yes,Yes,No,No,Yes,68,0,0,Ambulatory,NaN,NaN,1.33,4887,12.1,88.9,2.5,141,3,3.6,50,91,147,280,6.7,0.7,1,2.2,2.3,?,?,?,Dies
162,Male,No,Yes,No,No,No,No,Yes,No,Yes,Yes,Yes,No,Yes,Yes,No,?,?,?,?,No,No,Yes,65,?,48,Active,NaN,NaN,1.13,75,13.3,90,8,385000,4.3,0.6,53,52,164,181,7.5,1.46,5,18.6,?,?,?,?,Lives
163,Male,No,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,No,No,No,No,No,Yes,No,?,?,?,Yes,Yes,Yes,44,?,?,Ambulatory,NaN,NaN,2.14,94964,15.6,117.3,5200,118000,4.8,1.1,50,60,320,170,8.4,0.74,5,18,?,?,?,?,Dies
164,Male,Yes,Yes,No,No,No,Yes,Yes,No,Yes,No,No,No,No,No,No,No,?,Yes,Yes,No,Yes,Yes,52,50,?,Active,NaN,NaN,1.79,44340,12.7,95.8,14.4,412000,2.2,28.5,78,127,444,462,6.6,3.95,5,8.5,19.8,?,?,?,Dies

In [ ]:
hcc_data.replace('?', np.nan, inplace=True)
hcc_data

In [ ]:
hcc_data.columns

In [ ]:
hcc_datanumerical_cols = hcc_data[['Grams_day', 'Packs_year', 'INR', 'AFP', 'Hemoglobin', 'MCV', 'Leucocytes', 'Platelets',
                  'Albumin', 'Total_Bil', 'ALT', 'AST', 'GGT', 'ALP', 'TP', 'Creatinine', 'Nodules', 'Major_Dim',
                  'Dir_Bil', 'Iron', 'Sat', 'Ferritin','Class']]
hcc_datanumerical_cols

In [5]:
hcc_data.isna().sum()

NameError: name 'hcc_data' is not defined

In [6]:
hcc_data_subset.isna().sum()

NameError: name 'hcc_data_subset' is not defined

In [7]:
hcc_data.describe()

NameError: name 'hcc_data' is not defined

In [8]:
hcc_data.dtypes

NameError: name 'hcc_data' is not defined

In [9]:
# Converter cada coluna para numérico, tratando erros
for col in hcc_datanumerical_cols:
    # Verificar se a coluna é de tipo object, indicando possível presença de strings
    if hcc_datanumerical_cols[col].dtype == 'object':
        hcc_datanumerical_cols[col] = pd.to_numeric(hcc_datanumerical_cols[col].str.replace(' ', ''), errors='coerce')
    else:
        # Se não for object, converte diretamente
        hcc_datanumerical_cols[col] = pd.to_numeric(hcc_datanumerical_cols[col], errors='coerce')

NameError: name 'hcc_datanumerical_cols' is not defined

In [10]:
hcc_datanumerical_cols

NameError: name 'hcc_datanumerical_cols' is not defined

In [11]:
hcc_datanumerical_cols.dtypes

NameError: name 'hcc_datanumerical_cols' is not defined